タイムテーブル・講師詳細ページの作成
osokayama/osokayama.github.io pull request #154
Opened 2020-12-20 01:54 UTC by shizone

2020-12-20 02:00 UTC, makowis requested changes

2020-12-20 02:05 UTC, shizone commented on data/timetable_data.js
> +      title: '調整中',
> 　・可能であれば、今回のOSO2020のテーマ「エンジニアリング x ○○」になぞらえて、登壇者の方が考える「○○」に入るキーワードについてもご連絡いただけますでしょうか。
> 　　・難しい場合、実行委員の方で決定させていただくことも可能です。

タイトルとは別立てとしてこれをサイト上でどう見せるかみたいなのは要検討って感じですなあ

2020-12-20 02:14 UTC, makowis commented on data/timetable_data.js
> +      title: '調整中',
@shizone なるほどじゃあ置いときますか

2020-12-20 02:14 UTC, makowis approved these changes

2020-12-28 02:40 UTC, a-know commented
遅くなりましたプルリクありがとうございます！！！

以下、取り急ぎのメモです。どなたかできそうであれば対応していただけると嬉しいですし、もし難しそうであれば折をみて自分がやろうと思います！！

### タイムテーブルのところ
#### 今これなのを...
![スクリーンショット 2020-12-28 11 35 29](https://user-images.githubusercontent.com/1097533/103185800-541e5100-4901-11eb-9164-74708eeae04b.png)

#### こうしたい
![スクリーンショット 2020-12-28 11 37 18](https://user-images.githubusercontent.com/1097533/103185806-5a143200-4901-11eb-9d82-31a5735b9824.png)


### 詳細ページのところ
#### 今これなのを...
![スクリーンショット 2020-12-28 11 34 14](https://user-images.githubusercontent.com/1097533/103185822-65fff400-4901-11eb-9a18-a463539e3c4b.png)

#### こうしたい
![スクリーンショット 2020-12-28 11 34 34](https://user-images.githubusercontent.com/1097533/103185827-6bf5d500-4901-11eb-903f-3ef6405f6ec9.png)

2020-12-28 05:26 UTC, shizone commented
そうしました！

2020-12-28 05:54 UTC, a-know commented
すばやすぎる！！ありがとうございます！！！！

2021-01-05 00:43 UTC, a-know commented
@shizone
追加ありがとうございます！ローカルでも見ました、良さそうです。

一点、ここの部分なんですが、

![スクリーンショット 2021-01-05 9 42 37](https://user-images.githubusercontent.com/1097533/103593899-6f5d1200-4f3a-11eb-864f-51f25788c33f.png)

ここたぶんconnpassへのリンクが入ると思うんですが、このPull Request のマージのほうが先？でしょうか。

2021-01-05 00:45 UTC, shizone commented
@a-know あー同じタイミングで更新したいとこですね、いつやります？

2021-01-05 00:55 UTC, a-know commented
@shizone 
いつでも！nowでも！！

2021-01-05 01:15 UTC, makowis commented
@shizone @a-know マージしますよ？

2021-01-05 01:17 UTC, merged

2021-01-05 01:17 UTC, a-know commented
ありがとうございます！！